theme: jekyll-theme-minimal
title : Aleix Cambray
author :
  name : Aleix Cambray
  email : ac7914@imperial.ac.uk
  github : acambray
  feedburner : nil

plugins:
  - jekyll-seo-tag

google_analytics: UA-136520428-1
